// A real Overpass answer for central Paris (48.84,2.28,48.88,2.36), fetched
// 2026-10-09 from the maps.mail.ru Overpass mirror with a broader draft of the
// landmark filters (it still let memorial plaques and commercial galleries
// through, so the parser's own filter is tested on them), trimmed to a few
// elements and the tags the layer reads.

export const PARIS_LANDMARKS = {
  elements: [
    {
      type: 'node',
      id: 130102845,
      lat: 48.8570374,
      lon: 2.3118779,
      tags: {
        name: "Musée de l'Armée",
        'name:en': 'The Army Museum',
        tourism: 'museum',
        website: 'http://www.musee-armee.fr/',
        wikidata: 'Q1996069',
        wikipedia: "fr:Musée de l'Armée (Paris)",
      },
    },
    {
      type: 'node',
      id: 247584452,
      lat: 48.8631692,
      lon: 2.3329513,
      tags: {
        name: 'Musée des Arts Décoratifs',
        tourism: 'museum',
        website: 'https://madparis.fr/musee-des-arts-decoratifs',
        wikidata: 'Q1319378',
        wikipedia: 'fr:Musée des Arts décoratifs de Paris',
      },
    },
    {
      type: 'node',
      id: 247618453,
      lat: 48.8660977,
      lon: 2.3554138,
      tags: {
        name: 'Musée des Arts et Métiers',
        'name:en': 'Museum of Arts et Métiers',
        tourism: 'museum',
        website: 'https://www.arts-et-metiers.net',
        wikidata: 'Q1538826',
        wikipedia: 'fr:Musée des arts et métiers',
      },
    },
    {
      type: 'node',
      id: 4249899936,
      lat: 48.8601457,
      lon: 2.3421021,
      tags: {
        name: 'Musée en Herbe',
        tourism: 'museum',
      },
    },
    {
      type: 'node',
      id: 678802923,
      lat: 48.8612403,
      lon: 2.3448392,
      tags: {
        historic: 'memorial',
        memorial: 'plaque',
        name: 'Maison natale de Molière',
      },
    },
    {
      type: 'node',
      id: 678833516,
      lat: 48.861512,
      lon: 2.3423978,
      tags: {
        historic: 'memorial',
        memorial: 'plaque',
        name: 'Maison natale de Molière',
      },
    },
    {
      type: 'node',
      id: 570349020,
      lat: 48.8647358,
      lon: 2.2939065,
      tags: {
        historic: 'memorial',
        memorial: 'statue',
        name: 'Statue de George Washington',
        'name:en': 'George Washington Statue',
        start_date: '1900-07-03',
        wikidata: 'Q3497629',
        wikipedia: 'en:Equestrian statue of George Washington (Paris)',
      },
    },
    {
      type: 'node',
      id: 676907609,
      lat: 48.8492181,
      lon: 2.3413228,
      tags: {
        historic: 'memorial',
        memorial: 'statue',
        name: 'Statue de Saint-Louis',
      },
    },
    {
      type: 'node',
      id: 977195330,
      lat: 48.8431371,
      lon: 2.355922,
      tags: {
        name: 'Butte de Coupeaux',
        tourism: 'viewpoint',
      },
    },
    {
      type: 'node',
      id: 250657151,
      lat: 48.8643016,
      lon: 2.3480523,
      tags: {
        height: '27',
        man_made: 'tower',
        name: 'Tour de Jean-sans-Peur',
        start_date: '1409',
        'tower:type': 'defensive',
        website: 'http://www.tourjeansanspeur.com',
        wikidata: 'Q3533101',
        wikipedia: 'fr:Tour Jean-sans-Peur',
      },
    },
    {
      type: 'way',
      id: 5013364,
      center: {
        lat: 48.8582603,
        lon: 2.2945008,
      },
      tags: {
        height: '330',
        heritage: '3',
        historic: 'monument',
        man_made: 'tower',
        name: 'Tour Eiffel',
        'name:en': 'Eiffel Tower',
        operator: 'Société d’Exploitation de la Tour Eiffel',
        start_date: '1889',
        tourism: 'attraction',
        'tower:type': 'communication;observation',
        website: 'https://www.toureiffel.paris/',
        wikidata: 'Q243',
        wikipedia: 'fr:Tour Eiffel',
      },
    },
    {
      type: 'node',
      id: 910390736,
      lat: 48.8559492,
      lon: 2.3460263,
      tags: {
        historic: 'castle',
        name: 'Conciergerie',
        operator: 'Centre des monuments nationaux',
        tourism: 'museum',
        website: 'https://www.paris-conciergerie.fr',
        wikidata: 'Q138101',
        wikipedia: 'fr:Conciergerie de Paris',
      },
    },
    {
      type: 'way',
      id: 4208595,
      center: {
        lat: 48.856163,
        lon: 2.2978311,
      },
      tags: {
        leisure: 'park',
        name: 'Champ de Mars',
        'name:en': 'Field of Mars',
        tourism: 'attraction',
        website: 'https://www.paris.fr/lieux/parc-du-champ-de-mars-1807',
        wikidata: 'Q217925',
        wikipedia: 'fr:Champ-de-Mars (Paris)',
      },
    },
    {
      type: 'way',
      id: 4221369,
      center: {
        lat: 48.8440393,
        lon: 2.3596915,
      },
      tags: {
        heritage: '2',
        leisure: 'park',
        name: 'Jardin des Plantes',
        'name:en': 'Garden of the Plants',
        operator: "Muséum National d'Histoire Naturelle",
        tourism: 'attraction',
        website: 'https://www.jardindesplantesdeparis.fr/fr',
        wikidata: 'Q730948',
        wikipedia: 'fr:Jardin des plantes de Paris',
      },
    },
    {
      type: 'node',
      id: 274258609,
      lat: 48.872513,
      lon: 2.3148624,
      tags: {
        name: 'Lelong & Co.',
        tourism: 'gallery',
        website: 'https://www.galerie-lelong.com/',
      },
    },
  ],
};
